# Generated by Django 4.0.4 on 2022-05-25 17:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_toppings_pizzaorderapi_extra_toppings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorderapi',
            name='if_favourite',
            field=models.BooleanField(default=False, verbose_name='Любимый заказ?'),
        ),
        migrations.AlterField(
            model_name='pizzaorderapi',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 25, 17, 53, 37, 431841)),
        ),
        migrations.CreateModel(
            name='UserFavouriteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=65, verbose_name='Пользователь')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.pizzaorderapi', verbose_name='Любимый заказ')),
            ],
            options={
                'verbose_name': 'Любимый заказ пользователя',
                'verbose_name_plural': 'Любимые заказы пользователей',
            },
        ),
    ]
