# Generated by Django 4.0.4 on 2022-05-25 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pizzaorderapi_if_favourite_alter_pizzaorderapi_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzaorderapi',
            old_name='if_favourite',
            new_name='is_favourite',
        ),
        migrations.AlterField(
            model_name='pizzaorderapi',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 25, 17, 58, 23, 744727)),
        ),
    ]
