# Generated by Django 3.2.4 on 2021-06-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191227_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platterorder',
            name='food_type',
        ),
        migrations.RemoveField(
            model_name='platterorder',
            name='foodsize',
        ),
        migrations.RemoveField(
            model_name='saladorder',
            name='food_type',
        ),
        migrations.AlterField(
            model_name='price',
            name='food_type',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Sub', 'Sub'), ('Topping', 'Topping')], max_length=65),
        ),
        migrations.DeleteModel(
            name='PastaOrder',
        ),
        migrations.DeleteModel(
            name='PastaType',
        ),
        migrations.DeleteModel(
            name='PlatterOrder',
        ),
        migrations.DeleteModel(
            name='PlatterType',
        ),
        migrations.DeleteModel(
            name='SaladOrder',
        ),
        migrations.DeleteModel(
            name='SaladType',
        ),
    ]
