# Generated by Django 3.2.4 on 2021-06-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210612_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='food_type',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Topping', 'Topping')], max_length=65),
        ),
        migrations.DeleteModel(
            name='SubOrder',
        ),
        migrations.DeleteModel(
            name='SubTopping',
        ),
        migrations.DeleteModel(
            name='SubType',
        ),
    ]
