# Generated by Django 3.2.9 on 2022-04-24 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210613_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 24, 18, 18, 40, 327943)),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Ordered', 'Ordered'), ('Processing', 'Processing'), ('Sent', 'Sent'), ('Complete', 'Complete')], max_length=20),
        ),
    ]
